version: '3.9'

services:
  order:
    container_name: order_java
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/orders
      - DATABASE_USERNAME= postgres
      - DATABASE_PASSWORD= postgres
    depends_on:
      - db

  #old service (postgres)
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}